name: generate minecraft contribution chart

on:
    schedule:
        - cron: "0 */6 * * *"
    workflow_dispatch:
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  # Add the GITHUB_TOKEN secret to the step
                  token: ${{ secrets.TOKEN }}
            - name: Print working directory
              run: pwd
            - name: List everything on the working directory
              run: ls /home/runner/work/DanielSobrino/DanielSobrino
            - name: Install submodule dependencies
              run: npm install minecraft-contribution-chart-github/package.json
            - name: Generate the GIF
              env:
                  CONFIG_FILE: /home/runner/work/DanielSobrino/DanielSobrino/minecraft-contribution-chart-github/configChart.json
                  USERNAME: DanielSobrino
                  TOKEN: ${{ secrets.TOKEN }}
              run: npm start minecraft-contribution-chart-github/package.json
              
